### ISSUE TITLE
Element.className bug

### ISSUE THREAD

**Issue by oscarotero** [b-fuze/deno-dom#102]
Hi. In the version `0.1.28-alpha` the `className` property doesn't update the value if it was updated previously with `classList`:

```js
console.log(element.className); // foo
element.classList.add("bar");
console.log(element.className); // foo
```
In the previous version (`v0.1.27-alpha`) the className value was successfuly updated to `foo bar`.

**Comment by 0kku** [comment]
Thanks

**Comment by oscarotero** [comment]
Thanks for the quick fix. When is planned to tag a new version containing this fix?

**Comment by b-fuze** [comment]
I'll push it out now, mb

**Comment by oscarotero** [comment]
Thanks, it works fine now.
The only thing is that className now includes a space character:

```js
console.log(element.className); // "" (when it's empty, there's no space)
element.classList.add("bar");
console.log(element.className); // " bar" (has a space in the beginning)
```

**Comment by b-fuze** [comment]
Hrm... Yeah, @0kku looks like there's still one more thing

**Comment by 0kku** [comment]
Sigh… I could've sworn I checked for that.

**Comment by 0kku** [comment]
Should be fixed now.

**Comment by oscarotero** [comment]
It's perfect. Thanks!
