### ISSUE TITLE
Bug: insertBefore doesn't remove the inserted node from the original parent node

### ISSUE THREAD

**Issue by henningko** [b-fuze/deno-dom#107]
I am trying to unwrap a node (e.g. move all its content to the parent node), also see #106 

The easiest implementation would be something like this, with el being any element that has a parent
```ts
let parent = el.parentNode;
while (el.firstChild) parent.insertBefore(el.firstChild, el);
```
Also see
* https://plainjs.com/javascript/manipulation/unwrap-a-dom-element-35/
* https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes#remove_all_children_from_a_node

However, with deno-dom, this puts me into an infinite loop, as `el.firstChild` never returns a falsy value. I assume this is due to the underlying `childNodes` not being updated.

**Comment by b-fuze** [comment]
Which version of Deno DOM are you using? The `.childNodes` should definitely be live

**Comment by b-fuze** [comment]
I was able to reproduce it. I'll push a fix hopefully later today
