### ISSUE TITLE
Bug(?): NamedNodeMap missing `length`

### ISSUE THREAD

**Issue by henningko** [b-fuze/deno-dom#109]
Edit: Narrowed the problem down to missing `length` on `NamedNodeMap` (see comment below).

Hi,

I'm trying to build an article parser in deno, and I am using [`@mozilla/readability`](https://github.com/mozilla/readability) for it. Readability requires a parsed `Document` as its input.

When using jsdom (via `import { JSDOM } from "https://jspm.dev/npm:jsdom-deno@19.0.2";`), Readability performs just fine. When using `deno-dom`, images are dropped from parsed article. 

```js
import { Readability } from "https://cdn.skypack.dev/@mozilla/readability@0.4.1";
// import { JSDOM } from "https://jspm.dev/npm:jsdom-deno@19.0.2";
import { DOMParser } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";

const parseURL = new URL("https://ventureunlocked.substack.com/p/the-bull-market-is-over-what-are");
const htmlResponse = await fetch(parseURL.href);
const htmlData = await htmlResponse.text();

// For JSDOM:
// const { window: { document: doc }  } = new JSDOM(htmlData);

// For deno-dom:
const doc = new DOMParser().parseFromString(htmlBody, "text/html");

const reader = new Readability(doc); //, { debug: true }
const article = reader.parse();
```

Example URL to parse:
https://ventureunlocked.substack.com/p/the-bull-market-is-over-what-are

Seems odd, but maybe someone has an intuition on what's going on.

**Comment by henningko** [comment]
I think I may have found the culprit—in [readability.js](https://github.com/mozilla/readability/blob/1d2cb030b32e753cc4b7c4ce8b64c3ce4dc1b2ff/Readability.js#L1570), `attributes.length` is expected.
```js
    _unwrapNoscriptImages: function(doc) {
      var imgs = Array.from(doc.getElementsByTagName("img"));
      this._forEachNode(imgs, function(img) {
        for (var i = 0; i < img.attributes.length; i++) {
          var attr = img.attributes[i];
          switch (attr.name) {
            case "src":
            case "srcset":
            case "data-src":
            case "data-srcset":
              return;
          }
          if (/\.(jpg|jpeg|png|webp)/i.test(attr.value)) {
            return;
          }
        }
        img.parentNode.removeChild(img);
      });
[...]
```
`deno-dom` does not seem to have `length` defined for `NamedNodeMap`, causing all images to be removed.

**Comment by b-fuze** [comment]
I'm working on getting a fix for this

**Comment by b-fuze** [comment]
NamedNodeMap should be pretty spec compliant now. I confirmed that Readability doesn't remove the images with this fix. Thanks for reporting

**Comment by henningko** [comment]
Awesome, thank you! :-)
