### ISSUE TITLE
documet.innerHTML and document.outerHTML returns undefined.

### ISSUE THREAD

**Issue by a3har** [b-fuze/deno-dom#117]
Pardon me if I am ignorant ( Just starting out )

document parsing works as expected but is there a way to parse it back into a string ?
In normal JS, we can simply call `document.outerHTML`

If this has not been implemented yet. can I take it up ?

**Comment by b-fuze** [comment]
`Document` isn't an Element so it doesn't have an `.outerHTML` attribute. What you should use instead is `.documentElement` e.g.
```js
const html = document.documentElement.outerHTML;
```

**Comment by a3har** [comment]
Oh alright. Thank you very much.
