### ISSUE TITLE
Add map function to NodeList

### ISSUE THREAD

**Issue by bytooo** [b-fuze/deno-dom#119]
As the title says. I believe adding a map function to the NodeList class would be useful as I currently find myself pushing values from the `Document.querySelector().childNodes.forEach()` loop into an array defined previously instead of just defining the array as the result of an usual map function.

**Comment by 0f-0b** [comment]
If such a `map` function existed, how would `nodeList.map(fn)` be different from `Array.from(nodeList, fn)`?

**Comment by 0kku** [comment]
This is an [upstream issue](https://github.com/whatwg/webidl/issues/796). The current spec doesn't specify a `map()` method on `NodeList` and we're not looking to add methods that are in contravention of the DOM spec.

**Comment by bytooo** [comment]
> If such a `map` function existed, how would `nodeList.map(fn)` be different from `Array.from(nodeList, fn)`?

It wont be but in my opinion .map is much simpler an clean

**Comment by 0kku** [comment]
Presumably, the difference would be that it would return a `NodeList`, and not an `Array`. Unless `NodeList` had a [`Symbol.species` getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species) that returned `Array` for whatever reason, `map()` would return a new instance that matches the target instance. However, currently, `NodeList` does not extend `Array`, and therefore does not have all the same methods available.

While I recognize that there are many things that would be convenient to have in the DOM API, this project's goal is to implement it as specified in the specification. You may employ a third party library that is designed to make dealing with the DOM easier and use that in conjunction with this project. If you wish to see the quality of life features you propose in deno-dom, you need to advocate for their addition to the DOM specification over at [WHATWG](https://github.com/whatwg/).

**Comment by bytooo** [comment]
> Presumably, the difference would be that it would return a `NodeList`, and not an `Array`. Unless `NodeList` had a [`Symbol.species` getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species) that returned `Array` for whatever reason, `map()` would return a new instance that matches the target instance. However, currently, `NodeList` does not extend `Array`, and therefore does not have all the same methods available.
> 
> 
> 
> While I recognize that there are many things that would be convenient to have in the DOM API, this project's goal is to implement it as specified in the specification. You may employ a third party library that is designed to make dealing with the DOM easier and use that in conjunction with this project. If you wish to see the quality of life features you propose in deno-dom, you need to advocate for their addition to the DOM specification over at [WHATWG](https://github.com/whatwg/). 

Thank you for your detailed reply
