### ISSUE TITLE
[Feature Request] Add support for arm64 Linux distros

### ISSUE THREAD

**Issue by andresrcs** [b-fuze/deno-dom#122]
Can you please consider providing a binary for arm64? I know I can build it natively with Rust but my issue is with another application that has Deno DOM as a dependency and the installation script downloads from your releases.

**Comment by b-fuze** [comment]
Yeah, I can look into that. Also, if you don't mind, what's the dependency?

**Comment by andresrcs** [comment]
I'm trying to install [Quarto](https://quarto.org/) on Ubuntu 22.04 arm64 and this software depends on Deno (for which [LukeChannings](https://github.com/LukeChannings/deno-arm64/releases) offers arm64 binaries) and Deno DOM, the installation script downloads from your GitHub repository so I think I can get away with just replacing the file name to point to an arm64 built.

**Comment by b-fuze** [comment]
If you have another binary you can use the `DENO_DOM_PLUGIN` environment variable to override the plugin location, assuming that Deno is being run with `--allow-env` or similar

**Comment by andresrcs** [comment]
Thanks, I read that in the documentation but I would rather not modify Quarto too much and, honestly, I don't quite understand how and for what Deno is used for, I'm only interested in getting Quarto's functionalities on arm64.

**Comment by b-fuze** [comment]
@andresrcs it should work now, lmk how it goes
