### ISSUE TITLE
Get multiple selectors in order?

### ISSUE THREAD

**Issue by tmikaeld** [b-fuze/deno-dom#127]
Is it possible to retrieve multiple selectors in DOM order?

For example, I need headers, paragraphs, div texts, images and links in the order they appear in.

**Comment by 0kku** [comment]
```ts
const elements = doc.querySelectorAll("h1, p, div, img");
```?

**Comment by 0kku** [comment]
```ts
const elements = doc.querySelectorAll("h1, p, div, img");
```?

**Comment by tmikaeld** [comment]
Oh god, I read too fast, this is the standard DOM interface, not a custom scraper.

Thanks 😶‍🌫️
