### ISSUE TITLE
querySelector fails with nested element

### ISSUE THREAD

**Issue by theduke** [b-fuze/deno-dom#13]
The following querySelector use fails:

```typescript
import * as dom from "https://deno.land/x/deno_dom@v0.1.2-alpha4/deno-dom-wasm.ts";

const txt = `<!DOCTYPE html>
<html>
<body>
    <a></a>
</body>
</html>`;
const doc = new dom.DOMParser().parseFromString(txt, 'text/html');
if (doc) {
    const el = doc.querySelector('.maincolumn--user a');
} else {
    throw new Error('could not parse');
}

```

Trace:
```
error: Uncaught TypeError: e.getAttribute is not a function
    at Array.Resolver (eval at compile (https://deno.land/x/deno_dom@v0.1.2-alpha4/src/dom/nwsapi.js:766:17), <anonymous>:3:172)
    at collect (https://deno.land/x/deno_dom@v0.1.2-alpha4/src/dom/nwsapi.js:1559:21)
    at _querySelectorAll (https://deno.land/x/deno_dom@v0.1.2-alpha4/src/dom/nwsapi.js:1516:36)
    at Object._querySelector [as first] (https://deno.land/x/deno_dom@v0.1.2-alpha4/src/dom/nwsapi.js:1422:14)
    at HTMLDocument.querySelector (document.ts:184:24)
```

`deno`: `1.3.3` ( NixOS does not have a `1.4` package yet)

**Comment by b-fuze** [comment]
Can you provide an HTML sample to work with

**Comment by theduke** [comment]
Narrowing this down was interesting...

```html
<!DOCTYPE html>
<html>
<body>
    <a></a>
</body>
</html>
```

**Comment by theduke** [comment]
I should add that I was using `v0.1.2-alpha4`.

**Comment by theduke** [comment]
Narrowing this down proofed quite interesting...

I updated the first comment with a self-contained example.

**Comment by b-fuze** [comment]
Alright, fixed in ebc06c658a5e04cc1f50269602d0bd37a6d4c9e0

**Comment by theduke** [comment]
Cheers.

Have you investigated if some other libraries like `jsdom` have a comprehensive test suite that could be incorporated?

**Comment by CodingCarter** [comment]
> Cheers.
> 
> Have you investigated if some other libraries like `jsdom` have a comprehensive test suite that could be incorporated?

I have been working on a ton of tests using [Rhum](https://deno.land/x/rhum@v1.1.4), but I only have tests for the `Element` and `Node` class thus far.  I will probably send a PR within two-three weeks as I am working hard on a different module currently.

**Comment by b-fuze** [comment]
I plan to incorporate WPT tests as Deno DOM's primary test suite.
________________________________
