### ISSUE TITLE
deno-dom-native throws error about explort Plug

### ISSUE THREAD

**Issue by Sembiance** [b-fuze/deno-dom#131]
```
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/plug/mod.ts' does not provide an export named 'Plug'
import { Plug } from "https://deno.land/x/plug/mod.ts";
         ^
    at <anonymous> (https://deno.land/x/deno_dom@v0.1.36-alpha/deno-dom-native.ts:1:10)
```

Looks like the `Plug` export stopped being available in version `0.5.2`

If I manually change the import line to `import { Plug } from "https://deno.land/x/plug@0.5.2/mod.ts";` then it works ok, so that could be a quick workaround.

**Comment by nhrones** [comment]
Same here on Windows10 W/latest Deno 1.29.4
I get the following error:
```
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/plug/mod.ts' does not 
provide an export named 'Plug'
import { Plug } from "https://deno.land/x/plug/mod.ts";
         ^
    at <anonymous> (https://deno.land/x/deno_dom@v0.1.36-alpha/deno-dom-native.ts:1:10) 
```
I can run the examples with `deno-dom-wasm` and with `deno-dom-wasm-noinit` with no errors or issues.

Also, I've tried a few other deno libs recently that have produced this exact same error message about `Plug`.

**Comment by b-fuze** [comment]
Thanks
