### ISSUE TITLE
Support for stringify

### ISSUE THREAD

**Issue by vwkd** [b-fuze/deno-dom#142]
Please add support to stringify a parsed DOM back into HTML.

This is useful to manipulate or rewrite HTML.

**Comment by b-fuze** [comment]
To serialize the document to a string you can use the `.outerHTML` property:
```typescript
const htmlString = "<DOCTYPE html>\n" + doc.documentElement.outerHTML;
```

**Comment by vwkd** [comment]
Too easy, missed that. Sorry!
