### ISSUE TITLE
Weird space is added when `document.body.outerHTML`

### ISSUE THREAD

**Issue by BlackAsLight** [b-fuze/deno-dom#156]
Give this HTML _which is the default format my IDE gives the html document_
```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<script type="module" src="/js/main.min.js"></script>
</head>

<body>
	<h1>Hello World</h1>
</body>

</html>
```
It gets a weird format when stringifying the file as `'<!DOCTYPE html>\n' + doc.documentElement!.outerHTML`
```html
<!DOCTYPE html>
<html lang="en"><head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<script type="module" src="/js/main.min.js"></script>
</head>

<body>
	<h1>Hello World</h1>



</body></html>
```
It works fine if there was no extra spacing anywhere, like if the file was minified before being parsed.

It would be much more appreciated if whatever output it did give was consistent, where the input format was irrelevant to the output format.

**Comment by b-fuze** [comment]
This is due to the deno-dom being standards-compliant. You can view the same output when you run it through a browser
![image](https://github.com/b-fuze/deno-dom/assets/10504957/cc1ba20d-e661-4d08-ab0a-8abefb45861a)

**Comment by BlackAsLight** [comment]
That's unfortunate, but I guess its not a bug...
