### ISSUE TITLE
Implement querySelector/querySelectorAll on Element

### ISSUE THREAD

**Issue by domolicious** [b-fuze/deno-dom#16]
I tried the following code and noticed querySelector/querySelectorAll wasn't implemented on Element. Personally I use that function for a more narrow scope when querying for elements and nodes. I cloned the repo and tried to add it myself, like it is in Document, but ran into one error after another until I didn't know how to solve it anymore. It would be great if you could add them!

```ts
import { DOMParser, Element } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";    
    
const doc = new DOMParser().parseFromString(`    
  <h1>Hello World!</h1>    
  <p>Hello from <a href="https://deno.land/">Deno!</a></p>    
`, "text/html")!;    
    
const p = doc.querySelector("p")!;    
    
console.log(p.querySelector("a")); // error: TS2339 [ERROR]: Property 'querySelector' does not exist on type 'Element'.
```

**Comment by b-fuze** [comment]
Hi,

I just implemented it in adaa5a587f9334a2f636d155efcbe5d716a900bc, try it out and see if it works properly. cheers

**Comment by domolicious** [comment]
Works like a charm! Thank you

**Comment by seethroughdev** [comment]
Hi, this works well for me too.  However, it appears like the linter is not seeing the type.  Using `v0.1.36-alpha`.

`[{
	"owner": "deno",
	"code": "2339",
	"severity": 8,
	"message": "Property 'querySelector' does not exist on type 'Node'.",
	"source": "deno-ts",
}]`

**Comment by b-fuze** [comment]
@seethroughdev that type error looks correct, the `Node` class does not implement the `querySelector` method. However, its descendants `Element` and `Document` _do_ implement the method. It's hard to tell what caused your error without seeing actual code.

**Comment by seethroughdev** [comment]
Ah, I see.  That makes sense @b-fuze .  So after my `Node` is returned, I need to get the `Element` of the node it sounds like.  

* I was using a `querySelectorAll` and wanting to iterate over the `NodeList` it returns using the same API.

**Comment by b-fuze** [comment]
@seethroughdev for `querySelectorAll` you'd need to cast `item` to an `Element`. For example
```ts
import { Element } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";
// ...
document?.querySelectorAll("items")?.forEach((item) => {
  const element = item as Element;
  const divChild = element.querySelector("div"); // This should work
});
```

**Comment by seethroughdev** [comment]
This works perfectly.  Thanks again @b-fuze !
