### ISSUE TITLE
How can this function return null?

### ISSUE THREAD

**Issue by pihentagy** [b-fuze/deno-dom#163]
https://github.com/b-fuze/deno-dom/blob/ee4e7d268f75fcf61b2d03679ef5f52b2aca5ff3/src/dom/dom-parser.ts#L17

Just curious how can it be null?

It will fail earlier, with other error.

**Comment by b-fuze** [comment]
@pihentagy good point, I have no idea why its signature says that it can return null... I thought that I might have found something in the spec saying so, but just seems like a mistake on my part. I resolved that in 3f6ca910d3c17231f7a3cfdf06979af468dda2f4

**Comment by pihentagy** [comment]
Thanks, that was quick. And needed a lot of test changes.

What is your release strategy (so when can one expect next release)?

**Comment by b-fuze** [comment]
I'm not following any particular release strategy currently since my updates are so sporadic. Probably sometime today or tomorrow I'll make a new release

**Comment by b-fuze** [comment]
As part of #164 I've already released this change in v0.1.47 to both deno.land/x and JSR so closing this
