### ISSUE TITLE
`linkElement.getAttribute("href")` works, but `linkElement.href` returns undefined

### ISSUE THREAD

**Issue by ooker777** [b-fuze/deno-dom#165]
```ts
import { DOMParser } from "jsr:@b-fuze/deno-dom";

const html = '<link rel="canonical" href="example"/>'
const document = new DOMParser().parseFromString(html, "text/html");
const linkElement = document.querySelector("link[rel='canonical']") as HTMLLinkElement | null

console.log(linkElement?.getAttribute("href")) // "example" 
console.log(linkElement?.href);                // undefined
```
The last one should works. See [HTMLLinkElement - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement "HTMLLinkElement - Web APIs | MDN") and [MDN playground](https://developer.mozilla.org/en-US/play?id=X3gSRMapAdmg0nxVJQwQjnj69EpCnPc7%2BqCvK%2FVd%2Fnhp8zWtkC6NO6MgAcu2Z3eT%2BSCtypUuui0DuSG1)

**Comment by b-fuze** [comment]
Duplicate issue of #72
