### ISSUE TITLE
HTML in Template Tag is Deleted from outerHTML

### ISSUE THREAD

**Issue by jon49** [b-fuze/deno-dom#18]
When output the `outerHTML` of a `template` tag it deletes the internal `html`.

```typescript
import { DOMParser, Element } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";

const html = `
<body>
   <template id="error-message-template">
      <snack-bar class=show><p slot="message"></p></snack-bar>
   </template>
</body>
`

const doc = new DOMParser().parseFromString(html, "text/html")!;

console.log(doc.documentElement?.outerHTML)
```

Really cool project. Can't wait until it gets out of alpha!

Output:

```html
<html><head></head><body>
   <template id="error-message-template"></template>

</body></html>
```

In the browser it does this:

```javascript
console.log(document.body.outerHTML)
```

```html
<body>
   <template id="error-message-template">
      <snack-bar class="show"><p slot="message"></p></snack-bar>
   </template>

</body>
```

**Comment by b-fuze** [comment]
I can fix this, but I was also planning on implementing `DocumentFragment` before I fixed `<template>` elements' behaviour to match the browser. So right now `DocumentFragment` is a blocker for proper function of `<template>`.

**Comment by jon49** [comment]
No worries, it's still alpha and I'm not pitching in. So, whatever the time table you have is completely fine! I was just playing around with it to experiment with it and see if I could use it to create a quick and dirty HTML DSL. It's not quite ready yet and I should probably be using a parser combinator anyways. I just have a hard time understanding parser combinators, so I guess it is a good excuse to learn!

Thanks for your work on this library/tool!

**Comment by b-fuze** [comment]
No, it was just pretty slow. I'm working on an implementation for it that should land in a few weeks.

**Comment by oscarotero** [comment]
`DocumentFragment` is implemented in the latest version. Should this issue be closed or there's any work to do here yet?

**Comment by b-fuze** [comment]
This still isn't fixed. I'm getting around to it though

**Comment by pblzd** [comment]
Is there any way to get hands on the contained elements, meanwhile? `childNodes` appears to be empty no matter what I'm trying.

In any case: thank you for building this! Highly appreciated!

**Comment by sebastienfilion** [comment]
Thank you for the hard work. I would really appreciate this getting fixed soon. Can I do something to help?

**Comment by b-fuze** [comment]
It should work now, if there are any further issues lmk
