### ISSUE TITLE
Set repo website as deno.land/x module entry

### ISSUE THREAD

**Issue by sno2** [b-fuze/deno-dom#19]
It'd be great if @b-fuze could set the repository website as https://deno.land/x/deno_dom.

**Comment by b-fuze** [comment]
What are you talking about

**Comment by sno2** [comment]
1. go to the "code" section
2. click on the settings button next to the "about" section on the right
3. paste in "https://deno.land/x/deno_dom" into the website input

**Comment by b-fuze** [comment]
Oh, yeah. I misread your question.

**Comment by sno2** [comment]
Do you want me to just close this, or did you not have enough time to add the website url?

**Comment by 0kku** [comment]
He's busy, he'll get to it.
