### ISSUE TITLE
bundled version fail to import element

### ISSUE THREAD

**Issue by AlexanderMisel** [b-fuze/deno-dom#20]
I packaged demo dom wasm version with `deno bundle` and tried to run the example. I failed to import Element from that bundle.

**Comment by jonathan-richer** [comment]
Seems like it is an issue with deno's bundler. If you require the bundled version, you could add a line after it's been bundled:
```javascript
export { Element1 as Element };
```
Deno's bundler seems to have had lots of issues of this kind. But if you add this line ^^^^ it should work fine.

**Comment by b-fuze** [comment]
This is fixed in Deno Canary.
