### ISSUE TITLE
createDocumentFragment is needed 

### ISSUE THREAD

**Issue by AlexanderMisel** [b-fuze/deno-dom#21]
Libraries may need this API to add content before merging to the DOM tree.

**Comment by dansalias** [comment]
This is critical. Are we able to review/merge the provided PR please?

**Comment by b-fuze** [comment]
I didn't have time to review it at the time and forgot. Now the PR can't be merged cleanly without fixing the merge conflicts it has with the current codebase... I am thinking of an alternative implementation, so I'll probably close the PR when I get around to it.

**Comment by kristoferjoseph** [comment]
@b-fuze want me to fix up that PR or are you going to implement it in a different way?

**Comment by b-fuze** [comment]
Yes, I planned on implementing it a different way
