### ISSUE TITLE
Serialization doesn't match the spec

### ISSUE THREAD

**Issue by andreubotella** [b-fuze/deno-dom#23]
I noticed two cases where the `innerHTML` serialization doesn't match the spec:

- The "special handling for void elements" doesn't apply only to void elements, but to elements that [serialize as void](https://html.spec.whatwg.org/multipage/parsing.html#serializes-as-void), which include the deprecated elements `<basefont>`, `<bgsound>`, `<frame>` and `<keygen>`.
- `Text` nodes which are children of `<style>`, `<script>`, `<xmp>`, `<iframe>`, `<noembed>`, `<noframes>`, `<plaintext>` or `<noscript>` don't get escaped.

**Comment by b-fuze** [comment]
Thank you for pointing that out, I don't think I'll implement deprecated elements as mentioned in the last non-goal. But not escaping text nodes of specific elements is necessary and needs to be fixed.

**Comment by 0kku** [comment]
I suppose if someone _really_ wants support for the deprecated elements, we could accept a PR? At least in cases like these where they don't increase the complexity of the code in a significant way and doesn't impact performance etc. But yeah, I have no interest in putting work towards deprecated stuff myself.
