### ISSUE TITLE
Property 'forEach' does not exist on type 'NodeList'

### ISSUE THREAD

**Issue by drwpow** [b-fuze/deno-dom#29]
Hello! Great library! I am getting an error on `querySelectorAll()` in conjunction with `.forEach()`. Simple repo:

```ts
import { DOMParser } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";

const html = '<div class="div"></div><div class="div></div>';
const parser = new DOMParser();
const dom = parser.parseFromString(html, "text/html");
dom?.querySelectorAll(".div")?.forEach((el) => {
  console.log(el);
});
```

The error:

```
error: TS2339 [ERROR]: Property 'forEach' does not exist on type 'NodeList'.
dom?.querySelectorAll("div")?.forEach((el) => {
```

I can clearly see that `forEach` [is defined here](https://github.com/b-fuze/deno-dom/blob/fd7774b38abce90a895f9f9d95583646ffa5d149/src/dom/node-list.ts#L24), so I’m unsure where that type error is even coming from.

I’m on **Deno `1.5.3`**.

I should add that adding `// @ts-ignore` on that line works for now. So the library works great! It’s only a type that Deno can’t seem to find.

**Comment by b-fuze** [comment]
Oh thanks, forgot to add this to the interface here https://github.com/b-fuze/deno-dom/blob/fd7774b38abce90a895f9f9d95583646ffa5d149/src/dom/node-list.ts#L94
