### ISSUE TITLE
Element.removeAttribute() sets the attribute to null rather than to undefined

### ISSUE THREAD

**Issue by andreubotella** [b-fuze/deno-dom#30]
Or alternatively, the different `Element` APIs treat `null` and `undefined` in inconsistent ways.

```js
import { DOMParser } from "https://raw.githubusercontent.com/b-fuze/deno-dom/master/deno-dom-wasm.ts";

const document = new DOMParser().parseFromString(
  "<html attribute=value>",
  "text/html"
);

const html = document!.documentElement!;
html.removeAttribute("attribute");

console.log(html.hasAttribute("attribute"));    // true
console.log(html.getAttribute("attribute"));    // null
console.log(html.attributes.attribute);         // null

console.log(html.hasAttribute("nonexistent"));  // false
console.log(html.getAttribute("nonexistent"));  // null
console.log(html.attributes.nonexistent);       // undefined

// <html attribute><head></head><body></body></html>
console.log(html.outerHTML);
```

**Comment by b-fuze** [comment]
This would require proper implementation of `Attr` nodes and `.attributes` huh... Some quirky things those are...

**Comment by andreubotella** [comment]
Couldn't `removeAttribute` simply be changed to do `delete this.attributes[name]`?

**Comment by b-fuze** [comment]
Ye, you can do that. But I mean, wouldn't the proper thing to do would be to also implement and use `Attr` nodes too?

**Comment by andreubotella** [comment]
Since there seems to be a lot to keep track of in terms of liveness about `NamedNodeMap`, especially around how it interacts with the liveness of `DOMTokenNodes`, I'd prioritize having something that works now over implementing a more complicated API that seems little-used.

**Comment by jsejcksn** [comment]
> I personally don't care about `.attributes` at all, kinda wish it was deprecated but alas

@b-fuze What is your preferred way to enumerate the attributes of an element?

**Comment by b-fuze** [comment]
> > I personally don't care about `.attributes` at all, kinda wish it was deprecated but alas
> 
> What is your preferred way to enumerate the attributes of an element?

If I've ever needed to I'd use something like `Object.keys(elm.attributes)`, but I don't really need to do that as I usually know exactly what attribute I want or just use the JS DOM API.

**Comment by jsejcksn** [comment]
Translating XML to JSON is an really good use case for a DOM parser, and attribute enumeration is essential to that case.

**Comment by b-fuze** [comment]
Ah ye, definitely. Deno DOM doesn't support XML atm (though you could try using the HTML parser... If you're okay with that anyway). Also, turns out `Object.keys` doesn't work on `.attributes` (another reasonto dislike it) 

I plan to implement an XML parser at some point, but I rarely encounter it in my work

**Comment by jsejcksn** [comment]
> Also, turns out `Object.keys` doesn't work on `.attributes` (another reason to dislike it)

You can just use the spread operator:

```js
const entries = [...elm.attributes].map(a => [a.name, a.value]);
const obj = Object.fromEntries(entries);
```

**Comment by b-fuze** [comment]
Yeah I figured it's through some iterator... But that goes back to why I think it's so backwards considering that it's functionally a dictionary structure that doesn't act like a dictionary (assuming a dictionary should allow you to enumerate its keys directly)

**Comment by jsejcksn** [comment]
> Then again this isn't the only weird thing in the DOM

😂 True.

> But that goes back to why I think it's so backwards considering that it's functionally a dictionary structure that doesn't act like a dictionary (assuming a dictionary should allow you to enumerate its keys directly)

Ah—I can see how this might feel unreasonable if you are expecting a dictionary. (But that's not the case since [`Element.attributes`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes) is a [`NamedNodeMap`](https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap) of [`Attr`](https://developer.mozilla.org/en-US/docs/Web/API/Attr)s, which is _much_ richer than a dictionary... which I'm sure you know since you are the primary author of this module.) You could get a dictionary by converting that code above into a function:

```ts
function attributeDictionary (element: Element): Record<string, string> {
  const entries = [...element.attributes].map(a => [a.name, a.value]) as [name: string, value: string][];
  return Object.fromEntries(entries);
}
```

_Note: ☝️ That's using `Element` from [`lib.dom.d.ts`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts)_

**Comment by 0kku** [comment]
While we can probably all agree that the DOM API is horrible in more ways than one and ideally we'd design a better API from the ground-up without the legacy baggage… This is probably not the best place to discuss that 😅

**Comment by jsejcksn** [comment]
@0kku Agree. The goal of the project is to match the DOM spec as closely as possible, right?

**Comment by 0kku** [comment]
> @0kku Agree. The goal of the project is to match the DOM spec as closely as possible, right?

Yes. I too share @b-fuze's grievances, but our goal is to follow the spec despite its faults. That way DOM abstraction libs that make life easier can be used without compatibility issues, and people who just want to go vanilla don't have to relearn anything.

**Comment by KaKi87** [comment]
Hello, I can't even call the `removeAttribute` method, my Deno says it's undefined ? Thanks

**Comment by KaKi87** [comment]
Thanks for this really fast answer, actually, it's as simple as that :
```js
import { DOMParser } from 'https://deno.land/x/deno_dom/deno-dom-wasm.ts';

const document = (new DOMParser()).parseFromString('<body><div data-remove-this></div></body>', 'text/html');

const divElement = document.querySelector('div');

divElement.removeAttribute('data-remove-this');
// -> error: Uncaught TypeError: divElement.removeAttribute is not a function
```
Thanks

**Comment by b-fuze** [comment]
@KaKi87 again, please [create a new issue](https://github.com/b-fuze/deno-dom/issues/new)

**Comment by oscarotero** [comment]
I'm having the same issue and need to use a `delete` here:
https://github.com/lumeland/lume/blob/master/plugins/inline.js#L29

I want to remove the `inline` boolean attribute, but after call `element.removeAttribute("inline")`, the html output returns the attribute again `<img src="..." inline>`.

**Comment by b-fuze** [comment]
Yeah, this is way overdue. I'll push a fix soon

**Comment by b-fuze** [comment]
Alright, should be fixed in the latest release now @oscarotero

**Comment by oscarotero** [comment]
Awesome, thanks for the quick fix!
