### ISSUE TITLE
Comments not included in inner/outerHTML

### ISSUE THREAD

**Issue by jjallaire** [b-fuze/deno-dom#36]
I noticed that when taking the `innerHTML` or `outerHTML` of an element that comments are excluded. Seems like this code just needs to add a case for `NodeType.COMMENT_NODE`:

https://github.com/b-fuze/deno-dom/blob/9a32e27ee2c6935b8f5755038c910f8426926611/src/dom/element.ts#L202

**Comment by b-fuze** [comment]
Good catch, thanks for reporting
