### ISSUE TITLE
Doesn't work with Deno compile

### ISSUE THREAD

**Issue by Hunam6** [b-fuze/deno-dom#40]
When compiling the example (`deno --unstable compile --unstable -A file.ts`) it throws:
```
error: ReferenceError: DOMParser is not defined
    at file://$deno$/bundle.js:2391:13
```

**Comment by jsejcksn** [comment]
@Hunam6 Do you get the same error with `deno bundle ...`? I've seen similar exceptions thrown by swc (the bundler used by deno during bundling and compiling). At any rate, providing a reproducible example will help triage your issue.

**Comment by Hunam6** [comment]
Sorry for the delayed response @jsejcksn.
> Do you get the same error with deno bundle ...?

Yes
> providing a reproducible example will help triage your issue.

Maybe I wasn't clear enough, I was talking about the example in the README file.

**Comment by b-fuze** [comment]
@Hunam6 @jsejcksn both are fixed in Deno Canary, which you can get with `deno upgrade --canary`. I don't have the time to pin down the exact cause, but that's a solution at least.

**Comment by jsejcksn** [comment]
> This isn't a problem with Deno DOM itself.

@Hunam6 swc is still stabilizing. Try searching for variations on "bundle", "bundler", "swc", etc. in the Deno repo issues, and you'll find evidence of what I mean.
