### ISSUE TITLE
Access to doctype from`document.doctype`

### ISSUE THREAD

**Issue by oscarotero** [b-fuze/deno-dom#42]
`document.doctype` should return the document type [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Document/doctype).

Right now, the only way to access to the doctype is from `document.childNodes[0]`.

**Comment by b-fuze** [comment]
What's your use-case for accessing the doctype?

**Comment by oscarotero** [comment]
I want to convert a document to string.

```js
const html = doctype(document.childNodes[0]) + "\n" + document.documentElement.outerHTML;

function doctype(node) {
  return `<!DOCTYPE ${node.name}`
         + (node.publicId ? ` PUBLIC "${node.publicId}"` : "")
         + (!node.publicId && node.systemId ? ' SYSTEM' : "")
         + (node.systemId ? ` "${node.systemId}"` : "")
         + ">";
}
```

**Comment by b-fuze** [comment]
Okay. I'll get around to it, but if you want to send a PR for it feel free. It'd be some getter somewhere around here https://github.com/b-fuze/deno-dom/blob/master/src/dom/document.ts#L152

**Comment by oscarotero** [comment]
Okay, I will.
Thank you!
