### ISSUE TITLE
implement HTMLElement.innerText

### ISSUE THREAD

**Issue by Kaiido** [b-fuze/deno-dom#44]
It seems [`HTMLElement.innerText`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) was thought about when [drafting the designs](https://github.com/b-fuze/deno-dom/blob/master/design.md#caching) but forgotten since then. 
I guess it could be a simple alias to `.textContent` since there is no rendering involved.

**Comment by ejsmith** [comment]
`innerText` is supposed to filter out things like scripts and other non-user visible content.

**Comment by b-fuze** [comment]
@ejsmith in browsers using `DOMParser` CSS doesn't apply, so I mirror that behaviour in Deno DOM. Observe `main.js` in this example https://gist.dumber.app/?gist=04003019076de935dd57a2f81932788b

**Comment by ejsmith** [comment]
Hmm... interesting. Seems to be against what this says: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext

**Comment by 0kku** [comment]
> Hmm... interesting. Seems to be against what this says: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext

See <https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText#value>. DenoDOM is not a browser and does not render anything, and therefore this is spec-compliant behavior.

**Comment by ejsmith** [comment]
I didn't expect it to render anything, but I did expect it to skip things like script blocks.

**Comment by 0kku** [comment]
You'll need to take that up with [WHATWG](https://whatwg.org/), I'm afraid.

**Comment by ejsmith** [comment]
I'm not saying to go against whatever the spec is, the link I pointed to above seems to say that `innerText` is only supposed to show user visible text.

**Comment by 0kku** [comment]
The part I was linking was this: 

> A [DOMString](https://developer.mozilla.org/en-US/docs/Web/API/DOMString) representing the rendered text content of an element. If the element itself is not [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered) (e.g detached from the document or is hidden from view), the returned value is the same as the [Node.textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) property.

It's specified in [HTML§3.2.7](https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute):

> The innerText and outerText getter steps are:
>
> 1. If [this](https://heycam.github.io/webidl/#this) is not [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered) or if the user agent is a non-CSS user agent, then _return [this](https://heycam.github.io/webidl/#this)'s [descendant **text content**](https://dom.spec.whatwg.org/#concept-descendant-text-content)_.
> 
> **Note:** This step can produce surprising results, as when the `innerText` getter is invoked on an element not [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered), its text contents are returned, but when accessed on an element that is [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered), all of its children that are not [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered) have their text contents ignored.

(emphasis mine)
