### ISSUE TITLE
canvas.getContext() is not available

### ISSUE THREAD

**Issue by Srabutdotcom** [b-fuze/deno-dom#47]
@b-fuze ,.

I tried to create canvas element but cannot use getContext() after that.,
are getContext() not available yet or is there any other method to get canvas context.?

Thanks

**Comment by b-fuze** [comment]
Nah, it's not implemented and probably won't be unless Deno themselves implement it. If they do, I may try integrating Deno's native implementation. Deno DOM is primarily intended to help with HTML parsing and serialization, with a future goal of assisting some libraries with SSR (server-side rendering). Implementing the canvas API does not coincide with the overall goals of Deno DOM.
