### ISSUE TITLE
bug: native backend do not work with Deno 1.10.2

### ISSUE THREAD

**Issue by Hunam6** [b-fuze/deno-dom#48]
I'm not sure if it's related to Deno or not, but the native backend doesn't seem to work with Deno 1.10.2.
I tried on the README example on Windows and Linux (WSL) and it always gives this error:

![image](https://user-images.githubusercontent.com/38606542/118899517-2f0d9780-b90f-11eb-8532-2ae27d161a7c.png)

**Comment by b-fuze** [comment]
Yeah, the native backend is a bit broken right now, also Deno's native plugin interface is a bit bugged as well... When I get some time I'll look into it

**Comment by b-fuze** [comment]
@Hunam6 it should work now, please let me know

**Comment by Hunam6** [comment]
The example work perfectly but in my project it doesn't, it just closes silently with no apparent errors.
I'm on Windows and my project is https://github.com/Hunam6/Goodgle.
I'll try to make a small reproducible repo but I have no idea where to start so if you have an idea let me know.
I also tried running it with `--log-level debug` but didn't see anything suspect:
![image](https://user-images.githubusercontent.com/38606542/119426229-1d5e3280-bd09-11eb-9a9b-b7049229cffb.png)

**Comment by b-fuze** [comment]
Ah yes, it's segfaulting... Switch to WASM for now instead, it seems Deno's native plugin implementation is still bugged

**Comment by b-fuze** [comment]
I forgot to mention, but Deno DOM native works now in the latest versions... So I'm closing this and #63
