### ISSUE TITLE
Question about modifying a node

### ISSUE THREAD

**Issue by felixsanz** [b-fuze/deno-dom#60]
Is there an easy way to modify a node after it's parsed? I ask this because nodes contain childNodes, parentNode, parentElement, _ancestors, etc. Do i need to relink all those things or there is a method/way to replace one node with another?

**Comment by b-fuze** [comment]
Yes, Deno DOM implements `replaceWith` https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith

**Comment by felixsanz** [comment]
> Yes, Deno DOM implements `replaceWith` https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith

i didn't know it! big thanks!!!!!
