### ISSUE TITLE
Support for Deno v1.13 FFI

### ISSUE THREAD

**Issue by jjallaire** [b-fuze/deno-dom#63]
With the release of v1.13 Deno has replaced their native Rust plugin system with a more generic FFI interface (https://deno.com/blog/v1.13#experimental-ffi-replaces-native-plugin-system). Sadly `Deno.openPlugin` is now gone so `deno_dom` doesn't work w/ v1.13 and higher.

Are there plans to implement an FFI compatible version of `deno_dom`? We'd be happy to contribute to this effort if you can point us in the right direction.

**Comment by b-fuze** [comment]
Yes, I plan to implement it. If you're interested you can take a jab at it. However, it doesn't support buffers yet. It can only pass number types. When they implement buffers I'll definitely get the native backend working again.

For reference, here's the (open as of this writing) PR tracking string and buffer support for the new FFI interface https://github.com/denoland/deno/pull/11648

**Comment by jjallaire** [comment]
Okay, great to know that FFI is on your radar and hope that the string and buffer support lands soon.

I think that https://github.com/b-fuze/deno-dom/issues/64 would likely be enough for us until FFI lands, in the case that we did also want to try using the native plugin version (as that would give us the perf win both at load time for `deno_dom` code path and of course at runtime) do you still have reservations about the Deno plugin system stability? (saw these noted here: https://github.com/b-fuze/deno-dom/issues/48). We'd be running with Deno v1.12.2 (the last version to support native plugins).

**Comment by b-fuze** [comment]
> do you still have reservations about the Deno plugin system stability? 
Yes. The previous incarnation of the plugin system was very unstable. If you want to use the last stable version of the native plugin you'll need to use `v0.1.9-alpha` with Deno v1.9 as v1.10 introduced the new and buggy native plugin interface.

**Comment by jjallaire** [comment]
Okay in that case I think we’ll stick with WASM for now as we need some
bundler improvements introduced after v1.9

**Comment by b-fuze** [comment]
Deno DOM Native works with FFI now, closing this
