### ISSUE TITLE
Explicit loading of the WASM module

### ISSUE THREAD

**Issue by b-fuze** [b-fuze/deno-dom#64]
In regards to https://github.com/denoland/deno/issues/11916, Deno DOM WASM has a negative impact on startup performance. So I'm thinking of making a third entry-point (as an alternative to `deno-dom-wasm.ts`) that exposes an `init` function that explicitly initializes the HTML parser. If you try parsing HTML before initializing a parser Deno DOM will throw an error. 

Thoughts @jjallaire?

**Comment by jjallaire** [comment]
That would be absolutely be _huge_ for us as the scenarios where we need the faster startup time are for the most part not ones where we even load `deno_dom`. So yes that would be excellent and we'd use it right away.

**Comment by b-fuze** [comment]
Okay, I just added `deno-dom-wasm-noinit.ts` for explicit initializing of the WASM module. Check how to use it https://github.com/b-fuze/deno-dom#webassembly-startup-penalty

Let me know if there are any issues

**Comment by jjallaire** [comment]
Brilliant! Thank you :-) We are now using this variation and it cut 500ms off of our 850ms startup time (on a fairly recent MB Pro laptop so even more time on the average user system).
