### ISSUE TITLE
Support nativeWidth and nativeHeight image properties for lazy loading

### ISSUE THREAD

**Issue by tobiasschmidt89** [b-fuze/deno-dom#65]
Hello deno-dom Team,

it would be great if you could provide nativeWidth and nativeHeight properties on images.
This would allow to implement width and height on lazy loaded images in SSR/SSG.

e.g. in [Lume](https://lumeland.github.io/core/processors/) SSG I would like to use following script to add lazy loading with intrinsic width and height of images during server side processing:

```js
    const images = page.document.getElementsByTagName('img') // page.document uses deno-dom
    Array.from(images).forEach((image) => {
        image.setAttribute('loading', 'lazy')
        image.setAttribute('width', image.naturalWidth) // undefined
        image.setAttribute('height', image.naturalHeight) // undefined
    })
```

In case I run it in the browser like this it works and finds the sizes correctly. I guess deno-dom does not yet support it:
```js
    const images = document.getElementsByTagName('img')
    Array.from(images).forEach((image) => {
        image.setAttribute('loading', 'lazy')
        image.setAttribute('width', image.naturalWidth) // defined
        image.setAttribute('height', image.naturalHeight) // defined
    })
```

King regards
Tobias

**Comment by b-fuze** [comment]
I can implement it, but it will only return `0`. Deno DOM won't attempt to determine the size of any images.

**Comment by b-fuze** [comment]
Actually, I can't implement it yet because Deno DOM doesn't have HTML* constructors implemented for all the specific types... i.e. in this instance we'd need `HTMLImageElement`, but until that's implemented I can't add the `naturalWidth`/`naturalHeight` properties...

**Comment by henningko** [comment]
Hi @tobiasschmidt89 ,
Did you find a workaround? Running into the same issue. :-)
