### ISSUE TITLE
Doesn't work with moz-readability

### ISSUE THREAD

**Issue by ralyodio** [b-fuze/deno-dom#68]
```
import Readability from "https://cdn.esm.sh/v57/moz-readability@0.2.1/es2021/moz-readability.js"
import { DOMParser } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";


    const doc = new DOMParser().parseFromString(body, "text/html");
    const article = new Readability(doc).parse();
    console.log(article);

/// [uncaught application error]: TypeError - Cannot read properties of undefined (reading 'nextElementSibling')
```

Readbility needs a `window.document` object. Does deno_dom provide that?

**Comment by b-fuze** [comment]
Yes, the document returned by `parseFromString` is what would be referred to as `window.document`. Can you share a stack trace please

**Comment by ralyodio** [comment]
http://sprunge.us/BnZnYi

**Comment by ralyodio** [comment]
```
$ deno run -A --unstable --no-check ./app.ts
https://intechitec.com/i-underestimated-bitcoin-says-paypal-co-founder/
[uncaught application error]: TypeError - Cannot read properties of undefined (reading 'nextElementSibling')

request: {
  url: "http://localhost:8000/fetch?url=https://intechitec.com/i-underestimated-bitcoin-says-paypal-co-found...",
  method: "GET",
  hasBody: false
}
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at ee._cleanStyles (https://cdn.esm.sh/v57/moz-readability@0.2.1/es2021/moz-readability.js:3:17962)
    at ee._prepArticle (https://cdn.esm.sh/v57/moz-readability@0.2.1/es2021/moz-readability.js:3:6347)
    at ee._grabArticle (https://cdn.esm.sh/v57/moz-readability@0.2.1/es2021/moz-readability.js:3:13706)
    at ee.parse (https://cdn.esm.sh/v57/moz-readability@0.2.1/es2021/moz-readability.js:3:22976)
    at file:///home/ettinger/src/reader/app.ts:17:40
    at async dispatch (https://deno.land/x/oak@v9.0.1/middleware.ts:41:7)
    at async dispatch (https://deno.land/x/oak@v9.0.1/middleware.ts:41:7)
    at async dispatch (https://deno.land/x/oak@v9.0.1/middleware.ts:41:7)
    at async dispatch (https://deno.land/x/oak@v9.0.1/middleware.ts:41:7)
    at async EventTarget.#handleRequest (https://deno.land/x/oak@v9.0.1/application.ts:379:9)
```

I made a change. http://sprunge.us/6vjTB2

**Comment by ralyodio** [comment]
I'm wondering if the html comment on the first line is causing problems with your library.

**Comment by b-fuze** [comment]
The bug is caused by the fact that `firstElementChild` isn't implemented

**Comment by ralyodio** [comment]
how do we fix?

**Comment by sno2** [comment]
@b-fuze Are you going to fix this or can I take it?

**Comment by b-fuze** [comment]
Go ahead

**Comment by ralyodio** [comment]
I don't see it on deno.land yet

**Comment by sno2** [comment]
> 
> 
> I don't see it on deno.land yet

There hasn't been a new release yet.  You should be able to just pull from the github master like so if you want:

```ts
import { DOMParser } from "https://github.com/b-fuze/deno-dom/blob/master/deno-dom-wasm.ts";
```

Or lock the version of the code to the PR (#69) that fixed your issue to keep the module at the same version forever but not receiving updates:

```ts
import { DOMParser } from "https://github.com/b-fuze/deno-dom/blob/a83fc017366bf9e77cdb92640abfb1eea8d263e7/deno-dom-wasm.ts";
```

**Comment by ralyodio** [comment]
z I get this error:

```
Download https://github.com/b-fuze/deno-dom/blob/master/deno-dom-wasm.ts
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://github.com/b-fuze/deno-dom/blob/master/deno-dom-wasm.ts
  MediaType: Unknown
    at file:///home/ettinger/src/reader/app.ts:4:27
```

**Comment by ralyodio** [comment]
Looks like still missing something here:

```
https://www.nytimes.com/live/2021/11/05/business/jobs-report-stock-market-news
[uncaught application error]: TypeError - Cannot read properties of null (reading 'tagName')

```

**Comment by b-fuze** [comment]
@ralyodio please include a stack trace when you encounter an error.

**Comment by ralyodio** [comment]
That's it.

ALso I notice your parser never returns with this url:

https://ipinfo.io/ip

and a few others.https://www.bbc.com/news/uk-england-kent-59167648

**Comment by ralyodio** [comment]
any luck?

**Comment by chovyprognos** [comment]
https://github.com/mozilla/readability/issues/716#issuecomment-963530794

**Comment by b-fuze** [comment]
@ralyodio I know that some bug in Deno DOM is causing Readability to get stuck in an infinite loop. When I get some time I'll look into it

@chovyprognos thanks

**Comment by chovyprognos** [comment]
Thanks. Really appreciate it. It’s not something I know where to even begin. 

Anthony Ettinger 
(408) 656-2473

**Comment by b-fuze** [comment]
@chovyprognos alrighty... 86c7a679a0c05f354acf8b837cf05408e411dedf and 26d3a006a74ef53ae318c0c04868dd7e4ac62965 should fix the problems with moz-readability... They're part of the last Deno DOM release. Let me know if anything else comes up

**Comment by ralyodio** [comment]
looks like its working now, thank you!

**Comment by ralyodio** [comment]
This url causes moz-readability to hang.

https://www.bloomberg.com/news/articles/2021-11-13/apple-to-pay-30-million-over-security-checks-for-store-workers

**Comment by 0kku** [comment]
> This url causes moz-readability to hang.
> 
> https://www.bloomberg.com/news/articles/2021-11-13/apple-to-pay-30-million-over-security-checks-for-store-workers

Make sure you have the newest version of deno-dom: 
```
deno cache -r https://deno.land/x/deno_dom/deno-dom-wasm.ts
```
And then import up-to-date version of Readability: 
```ts
import { Readability } from "https://esm.sh/@mozilla/readability@0.4.1?no-check";
import { DOMParser } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";
```

We weren't able to reproduce the bug you describe.

**Comment by b-fuze** [comment]
@ralyodio thanks for reporting the other page with issues... I just pushed a fix for it, please test it with the latest version of Deno DOM. 

Use the following command to upgrade Deno DOM to the latest version as 0kku mentioned above:
```bash
deno cache -r https://deno.land/x/deno_dom/deno-dom-wasm.ts
```

Also, please keep all Deno DOM bugs related to Readability in this issue. We've confirmed that Readability itself shouldn't have any issues.

**Comment by jmherbst** [comment]
> Also, please keep all Deno DOM bugs related to Readability in this issue. We've confirmed that Readability itself shouldn't have any issues.

I'm running into this issue - Any chance you can take a look @b-fuze ?

Stack:
```javascript
» deno run --allow-net main.ts                                                                            
Check file:///Users/j/p/g/j/g/main.ts
error: Uncaught (in promise) TypeError: Cannot set property nodeValue of #<Node> which has only a getter
    at Readability$1.<anonymous> (https://ga.jspm.io/npm:@mozilla/readability@0.4.2/index.js:168:109)
    at Readability$1._removeNodes (https://ga.jspm.io/npm:@mozilla/readability@0.4.2/index.js:24:210)
    at Readability$1._removeScripts (https://ga.jspm.io/npm:@mozilla/readability@0.4.2/index.js:168:33)
    at Readability$1.parse (https://ga.jspm.io/npm:@mozilla/readability@0.4.2/index.js:266:937)
    at file:///Users/j/p/g/j/g/main.ts:19:24
```

`main.ts` :
```javascript
import { DOMParser } from 'https://deno.land/x/deno_dom/deno-dom-wasm.ts'
import { Readability } from 'https://ga.jspm.io/npm:@mozilla/readability@0.4.2/index.js'

const url = 'https://www.bloomberg.com/news/articles/2021-11-13/apple-to-pay-30-million-over-security-checks-for-store-workers';


const res = await fetch(url, {
  headers: {
    "User-Agent":
      "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
  }
});
const html = await res.text();
const document = new DOMParser().parseFromString(html, 'text/html');

const reader = new Readability(document);

const article = reader.parse();
try {
  console.log(article.content);
} catch (error) {
  console.log(error);
}
```

**Comment by henningko** [comment]
Since I didn't feel confident enough changing `deno-dom`, I fixed up Readability so that it works with `deno-dom`:
https://www.npmjs.com/package/readability-denodom

Particularly, the problem with images being lost due to the lacking NamedNodeMap iterator, see #109.

**Comment by henningko** [comment]
One other issue I just ran into: Readability wants the URL to be part of the `Document` (via `documentURI`). However, there's no way set the URI in `deno-dom`, since it's a read-only property and I can't find a way to set it via a constructor.

@b-fuze is there a way to set `Document.documentURI` that I'm missing?

**Comment by b-fuze** [comment]
@henningko nah, there isn't. You can create an issue for it, it sounds like something that I need to implement a deno-dom only API for.

**Comment by henningko** [comment]
Extended https://www.npmjs.com/package/readability-denodom to allow for a URL in the constructor as a workaround for now.

Will open an issue to keep it on your radar.
