### ISSUE TITLE
Errors from Using `--unstable` in Deno v1.4.0

### ISSUE THREAD

**Issue by CodingCarter** [b-fuze/deno-dom#7]
When running a file that is just importing the `DOMParser` with the `--unstable` flag, you get 3 errors (after accepting [my PR](https://github.com/b-fuze/deno-dom/pull/6) for adding the type to the import/export statements).  You also need the `--unstable` flag when using `deno-dom-native` because you are using the `openPlugin`.  The first one is due to the required type for import/export statements when you are re-exporting members and the other two are from the [checksum module](https://deno.land/x/checksum@1.4.0) which also needs you to `export type`.  Here are the errors in the log after you accept my PR:

```terminal
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { LogLevels, LevelName } from "./levels.ts";
                    ~~~~~~~~~
    at https://deno.land/std@0.61.0/log/mod.ts:13:21

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { HashAlgorithm } from "./hash.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/checksum@1.4.0/sha1.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { HashAlgorithm } from "./hash.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/checksum@1.4.0/md5.ts:1:1
```

I have already sent [a PR](https://github.com/manyuanrong/deno-checksum/pull/6) to the checksum repo to fix their issue, but we still need to fix the issue with the std module.

**Comment by ianfabs** [comment]
This can be temporarily allayed by adding the following to, or creating a new `tsconfig.json` with:

```json
{
  "compilerOptions": {
    "importsNotUsedAsValues": "remove",
    "isolatedModules": false
  }
}
```

and running your script with `-c ./tsconfig.json`

**Comment by b-fuze** [comment]
I fixed these errors in the recent commits, will need to prepare a release soon
