### ISSUE TITLE
Support Element Attribute-Binded Properties

### ISSUE THREAD

**Issue by sno2** [b-fuze/deno-dom#70]
Hello, the capability of supporting the various mixins defined in the spec for `Element` properties that reflect the value of an attribute would be useful for making `deno-dom` work for more libraries/applications that require them.  I would be interested in taking this task on for the various mixins (i.e. [`AriaMixin`](https://w3c.github.io/aria/#dom-ariamixin) for `Element`) with a clean approach of a helper method for defining these mixins and declaration merging for clean code:

```ts
interface Foo { n: string }

const defineName = (a: A) => a.n = "";

interface A extends Foo {}
class A implements Foo {
  constructor() {
    defineName(this);
  }
}

const asdf = new A();
console.log(asdf.n); // ""
```

[Typescript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN7JALmQGcwpQBzZAXwFgAoehdEE5AEwhlAgDk4BbFAF5kACjiEAggEpkQgHzI4AOhBzkAIg0BuevVCRYiFJOQQAHpBBsiaTDlp0EAGzhFbp4PwAOziIPBbDCxsemRkJhZSAFcEMHQoUVlQunDwji4QXgEIUTAAC2AiaV1U6npHRmZWNzYYdSyAd2RJJNLIonQ-ZWd0cnEiOtUSoA)

After that, we would simply need to use `Object.defineProperties` and map over an array of entries in the mixin when creating elements.  Let me know what y'all think, thanks.

**Comment by b-fuze** [comment]
What's the purpose and use-case of this?

**Comment by sno2** [comment]
> What's the purpose and use-case of this?

Making deno-dom follow the spec more closely and support more code that relies on these properties.

**Comment by sno2** [comment]
@b-fuze Never mind, this would probably really just be bloat in the code and Firefox willingly ignores these properties.
