### ISSUE TITLE
deno-dom + echarts for SSR: Cannot read properties of undefined (reading 'getComputedStyle')

### ISSUE THREAD

**Issue by mpope9** [b-fuze/deno-dom#74]
I'm trying to get SSR working with apache echarts and deno. I was initially trying to use `jsdom` but I can't get it to work due to exceeding stack space, so I'm trying out deno-dom. Not sure if this is currently possible to do this, and I'm new to deno. I am wondering if the error that I am seeing is an unimplemented feature or if I'm incorrectly setting up this library.

I am seeing this error:
```
>deno run priv/ssr/renderer_denodom.js
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getComputedStyle')
    at e._getSize (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/canvas/Painter.js:3:69983)
    at new e (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/canvas/Painter.js:3:61794)
    at new r (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/zrender.js:2:74605)
    at co (https://cdn.esm.sh/v58/zrender@5.2.1/deno/lib/zrender.js:2:77790)
    at new t (https://cdn.esm.sh/v58/echarts@5.2.2/deno/echarts.js:11:2339)
    at Module.use (https://cdn.esm.sh/v58/echarts@5.2.2/deno/echarts.js:11:21575)
    at file:///Users/pope/Projects/stats_5thq/priv/ssr/renderer_denodom.js:13:23
```

And here is the repro script:
```javascript
import * as echarts from "https://esm.sh/echarts@5.2.2";

import { DOMParser, Element } from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";

const doc = new DOMParser().parseFromString(`
<section class="row">
  <div id="graph" style="width: 100%;height:500px;"></div>
</section>
`, "text/html");

globalThis.document = doc

const root = doc.querySelector("div");

const chart = echarts.init(root, null);

```

The error is happening at `const chart = echarts.init(root, null);`.

The main source of this script is this gist for SSR + echarts + jsdom on Node: https://gist.github.com/pissang/4c32ee30e35c91336af72b129a1a4a73

**Comment by b-fuze** [comment]
The chart library seems to rely on the browser rendering engine seeing that it has a function called `_getSize` and that it is calling `getComputedStyle`. If you can't somehow disable that behavior, you may need to try another library.

**Comment by mpope9** [comment]
Thanks for the fast answer. Makes sense, I'll see if I can get around that some how. Would this be missing from Deno or deno-dom?

**Comment by 0kku** [comment]
Deno-dom is not a browser and is not trying to be one. It does not do layout, and therefore does not and cannot calculate the geometry of elements (which is what your library appears to be trying to do). There is no `getComputedStyle` implemented in deno-dom because deno-dom does not compute styles at all — only the DOM. Theoretically, that could be done in Deno, but that is out of scope for this library. If you need something that implements layout, you should probably look at something that runs an actual browser, such as Playwright or Puppeteer.

**Comment by mpope9** [comment]
@0kku Makes sense! Thank you for the explanation and suggestions!
