### ISSUE TITLE
set/get attributes?

### ISSUE THREAD

**Issue by ivanjeremic** [b-fuze/deno-dom#77]
Will this library soon support all APIs like set/get attributes? Also because it has the same goals as `jsdom` in node wouldn't it be easier to fork `jsdom` and make it deno compatible?

**Comment by b-fuze** [comment]
You can get and set attributes with `element.getAttribute("foo")` and `element.setAttribute("foo", "bar")` respectively. 

This module does not have the same goals as JSDOM, JSDOM aims to fully implement _all_ the browser APIs—to the point that it can act as a replacement for Puppeteer where it can even execute the Javascript contained therein. This module aims to stray _far_ from headless browser-like behaviour, and simply provides DOM APIs for the manipulation of HTML. 

So yeah, we have no plans to fork `jsdom`. Not to mention, we also get a browser-compliant HTML parser for free with `html5ever`.

**Comment by ivanjeremic** [comment]
Ok I think I have then something wrong with my code, ```
import {
  DOMParser,
  Element,
} from "https://deno.land/x/deno_dom/deno-dom-wasm.ts";

const doc = new DOMParser().parseFromString(
  `
  <h1>Hello World!</h1>
  <p>Hello from</p>
`,
  "text/html"
)!;

const p = doc.querySelector("p")!;

p.addAttribute("id", "XX");

// no attribute 
console.log(p.outerHTML);
```

Is there something like jsdom's `serialize`?

**Comment by b-fuze** [comment]
> Ok I think I have then something wrong with my code,

Yes, it's supposed to be
```js
p.setAttribute("id", "XX");
// Not
p.addAttribute("id", "XX");
```

> Is there something like jsdom's `serialize`?

No, but you can basically get the equivalent with
```js
const serialized = "<!DOCTYPE html>" + doc.documentElement.outerHTML;
```

**Comment by ivanjeremic** [comment]
> > Ok I think I have then something wrong with my code,
> 
> Yes, it's supposed to be
> 
> ```js
> p.setAttribute("id", "XX");
> ```
> 
> Not
> 
> ```js
> p.addAttribute("id", "XX");
> ```
> 
> As documented on MDN https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute
> 
> > Is there something like jsdom's `serialize`?
> 
> No, but you can basically get the equivalent with
> 
> ```js
> const serialized = "<!DOCTYPE html>" + doc.documentElement.outerHTML;
> ```

Oh how did I miss that :D I think it was late when I tried it. Thanks

**Comment by ivanjeremic** [comment]
@b-fuze What I found is that this does not work 

```
const doc = new DOMParser().parseFromString(tree, "text/html");

const els = doc .querySelectorAll("*");

 for (const el of els) {
  el.setAttribute("id", "random")
}
```

// Property 'setAttribute' does not exist on type 'Node'.

**Comment by b-fuze** [comment]
That looks like a TypeScript error and not an actual Javascript error. 

The issue is that `el` is a `Node` in TypeScript so you need to cast it to `Element` so that TypeScript can stop complaining. (`setAttribute` only exists on `Element`s, but `querySelectorAll` returns a `NodeList` and TypeScript doesn't know that it's returning a `NodeList` of `Element`s and not just nodes)

To fix it change to this
```js
(el as Element).setAttribute("id", "random")
```
