### ISSUE TITLE
`Document.createTreeWalker()` support?

### ISSUE THREAD

**Issue by aiotter** [b-fuze/deno-dom#82]
Do you have any plan to implement `Document.createTreeWalker()` method?
I wanted to delete all the text node with a specific content (`\n`) from the document, and I noticed it was not implemented yet.

**Comment by Hunam6** [comment]
see https://github.com/b-fuze/deno-dom/issues/35

**Comment by aiotter** [comment]
Woops sorry for that. I should have checked for duplicate issues more carefully. Thanks!
