### ISSUE TITLE
Last version not available in deno.land/x

### ISSUE THREAD

**Issue by oscarotero** [b-fuze/deno-dom#91]
Hi. I just realized the last version ([v0.1.22-alpha](https://github.com/b-fuze/deno-dom/releases/tag/v0.1.22-alpha), with support for document fragment) is not available in [deno.land/x/deno_dom](https://deno.land/x/deno_dom).

**Comment by b-fuze** [comment]
That is confusing... I'll investigate why it's not propagated to deno.land/x

Thanks for bringing it up

**Comment by b-fuze** [comment]
Apparently it's some caching issue on deno.land/x, it should be there now

**Comment by b-fuze** [comment]
Well, it's still not visible on the main page, but you can go there directly with https://deno.land/x/deno_dom@v0.1.22-alpha

**Comment by b-fuze** [comment]
Okay, it shows on the main page now

**Comment by oscarotero** [comment]
Great. Thank you!
