### ISSUE TITLE
Cannot redefine property: Symbol(Symbol.hasInstance)

### ISSUE THREAD

**Issue by dz4k** [b-fuze/deno-dom#92]
```
20:24:03.200 | TypeError: Cannot redefine property: Symbol(Symbol.hasInstance)
20:24:03.202 | at (https://deno.land/x/deno_dom@v0.1.21-alpha/src/api.ts:58:8)
```

Only seems to happen in the Cloudflare Pages build env, which is odd.

**Comment by b-fuze** [comment]
So this has come back rearing its ugly head 😩

What is this Cloudflare Pages that you speak of, and how are you running it?

**Comment by dz4k** [comment]
I have a [Lume](https://lume.land) site I deploy on [Cloudflare Pages](https://pages.cloudflare.com/) with the following build command: 

```sh
git fetch --unshallow && curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume/ci.ts
```

The site: https://github.com/dz4k/denizaksimsek.com

**Comment by dz4k** [comment]
Managed to reproduce it locally.

```console
$ deno --version
deno 1.20.6 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```

deno_dom@v0.1.21-alpha

**Comment by b-fuze** [comment]
@dz4k what code were you running?

**Comment by dz4k** [comment]
Minimal repro:

```ts
import "https://deno.land/x/deno_dom@v0.1.21-alpha/src/api.ts"
import "https://deno.land/x/deno_dom@v0.1.21-alpha/src/api.ts?v"
```

Seems like I was somehow importing the module twice. Since `Object.defineProperty` creates an unconfigurable property by default, the second time was failing.

**Comment by b-fuze** [comment]
Ah, I see... I should probably make it configurable then... Or check that it was included twice... Hrm

**Comment by b-fuze** [comment]
I'm making them configurable, thanks for reporting this
