### ISSUE TITLE
`.cloneNode(true)` loses `template` information

### ISSUE THREAD

**Issue by pblzd** [b-fuze/deno-dom#94]
#18 implemented `template` content handling, which is great!

Apparently the special information that an element is a `HTMLTemplateElement` gets lost when cloning a node, though. I'm using a `template` inside a `template` for looping over a list of items. After parsing, both `template`-elements are instances of `HTMLTemplateElement`. After `cloneNode(true)` on the first child of the outer template's content, the inner `template` is an instance of `Element`, though, and thus doesn't know anything about `.content`.

Is there anything I can change to avoid this? Without `cloneNode()` the whole templating-approach doesn't work.

Here's testing code to reproduce the issue. Step 3 fails, the "Actual" value is `Element`.

```javascript
import { DOMParser } from "https://deno.land/x/deno_dom@v0.1.23-alpha/deno-dom-wasm.ts";
import { assertEquals } from "https://deno.land/std@0.130.0/testing/asserts.ts";

Deno.test("template cloning", async (t) => {
  const doc = new DOMParser().parseFromString(`<html><body><template id="outer"><ul><template id="inner"><li></li></template></ul></template></body></html>`, "text/html");

  await t.step("outer", async () => {
    assertEquals(doc.querySelector("#outer").constructor.name, "HTMLTemplateElement");
  });
  await t.step("inner", async () => {
    assertEquals(doc.querySelector("#outer").content.children[0].querySelector("#inner").constructor.name, "HTMLTemplateElement");
  });
  await t.step("inner of cloned node", async () => {
    assertEquals(doc.querySelector("#outer").content.children[0].cloneNode(true).querySelector("#inner").constructor.name, "HTMLTemplateElement");
  });
});
```

**Comment by b-fuze** [comment]
Thanks
