### ISSUE TITLE
DOMTokenList is not indexable

### ISSUE THREAD

**Issue by Masamune903** [b-fuze/deno-dom#95]
As for some elements, `elem.querySelectorAll` doesn't work. When I check instantly, in `function makeRef(selectors, element)` at "/src/dom/selectors/nwsapi.js" and line 1328, `element.classList[0]` is used. `element.classList` is an instance of `DOMTokenList` and `DOMTokenList` extends `Set`, so we cannot get items as "`.classList[0]`". A native `DOMTokenList` acts as an `Array` so I want you to fix DOMTokenList.

I'm a Japanese student, so my sentence is so bad. I apologize.

**Comment by 0kku** [comment]
おつかれさまでした。Your English is fine.

So; it sounds like you're reporting two issues: 

1. What should be a `DomTokenList` is not indexable in deno-dom: 
```ts
const doc = new DOMParser().parseFromString("<div class='foo bar'></div>", "text/html");
doc.querySelector("div").classList[0]; // should return "foo" but returns undefined
```
2. The `:scope` pseudo-class selector is not supported:
```ts
doc.querySelector(":scope"); // should return <html> element of the document, but returns null
```

**Comment by 0kku** [comment]
#96 will address the first issue once it's ready for merging. 

I created a new issue for the second problem: #97.

**Comment by b-fuze** [comment]
Thanks to @0kku `DOMTokenList` _is_ fixed, however `:scope` is still broken due to a bug in the upstream dependency, `nwsapi`... Which is being tracked in #97
